name: DeepTracing
channels:
  - pytorch
  - defaults
  - bioconda
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anndata=0.10.5.post1=pyhd8ed1ab_0
  - anyio=4.8.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py39h8cd3c5a_5
  - arpack=3.9.1=nompi_h77f6705_101
  - array-api-compat=1.9.1=pyhd8ed1ab_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.4=pyhd8ed1ab_1
  - atk-1.0=2.38.0=hd4edc92_1
  - attrs=24.3.0=pyh71513ae_0
  - babel=2.16.0=pyhd8ed1ab_1
  - beautifulsoup4=4.12.3=pyha770c72_1
  - blas=1.0=mkl
  - bleach=6.2.0=pyhd8ed1ab_3
  - bleach-with-css=6.2.0=hd8ed1ab_3
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py39h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h3faef2a_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.2.1=py39h7633fee_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py39hf88036b_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.3=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.0=py39h9399b63_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - gdk-pixbuf=2.42.10=h05c8ddd_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.13=h59595ed_1003
  - graphviz=9.0.0=h78e8752_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtk2=2.24.33=h280cfa0_4
  - gts=0.7.6=h977cf35_4
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.1.0=pyhd8ed1ab_1
  - h5py=3.6.0=py39ha0f2276_0
  - harfbuzz=8.3.0=h3d44ed6_0
  - hdf5=1.10.6=h3ffc7dd_1
  - hpack=4.0.0=pyhd8ed1ab_1
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_1
  - icu=73.2=h59595ed_0
  - idna=3.7=py39h06a4308_0
  - igraph=0.10.15=he44f51b_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.18.1=pyh707e725_3
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py39hf3d152e_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.11.0=pyhd8ed1ab_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leidenalg=0.10.2=py39h3d6467e_0
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=8_h3b12eaf_netlib
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.9.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgd=2.3.3=h695aa2c_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=8_h3b12eaf_netlib
  - libleidenalg=0.11.1=h00ab1b0_0
  - libllvm11=11.1.0=he0ac6c6_5
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.0=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - librsvg=2.56.3=he3f83f7_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvmlite=0.39.1=py39h7d9a04d_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py39h9399b63_1
  - matplotlib=3.4.3=py39h06a4308_0
  - matplotlib-base=3.4.3=py39hbbc1b5f_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.0=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=8.4.0=h29a9f33_1
  - natsort=8.4.0=pyhd8ed1ab_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.5=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2=pyhd8ed1ab_0
  - notebook=7.4.5=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.56.4=py39h61ddf18_0
  - numexpr=2.8.7=py39h85018f9_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.5.4=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhff2d567_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.14=ha41ecd1_2
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhff2d567_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.0.0=py39hfdbf927_0
  - pip=24.2=py39h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - ply=3.11=py39h06a4308_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.1.1=py39h8cd3c5a_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pygraphviz=1.11=py39h7ef11f9_2
  - pynndescent=0.5.13=pyhff2d567_0
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pyreadr=0.5.0=py39h9037f83_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.20=he870216_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-graphviz=0.20.3=pyh91182bf_2
  - python-igraph=0.11.5=py39hc9390a5_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-louvain=0.16=pyhd8ed1ab_1
  - python_abi=3.9=2_cp39
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py39h06a4308_0
  - pyyaml=6.0.2=py39h8cd3c5a_1
  - pyzmq=26.2.0=py39h4e4fb57_1
  - qt-main=5.15.2=hb6262e9_11
  - readline=8.2=h5eee18b_0
  - referencing=0.36.1=pyhd8ed1ab_0
  - requests=2.32.3=py39h06a4308_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.22.3=py39he612d8f_0
  - scanpy=1.9.1=pyhd8ed1ab_0
  - scikit-learn=1.5.2=py39h4b7350c_1
  - scipy=1.10.1=py39h7360e5f_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - send2trash=1.8.3=pyh0d859eb_1
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=75.1.0=py39h06a4308_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.2=py39hd92a3bb_0
  - stdlib-list=0.11.0=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.18.1=pyh0d859eb_0
  - texttable=1.7.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py39h06a4308_0
  - torchaudio=0.11.0=py39_cu113
  - torchvision=0.12.0=py39_cu113
  - tornado=6.4.1=py39h5eee18b_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - umap-learn=0.5.7=py39hf3d152e_0
  - unicodedata2=15.1.0=py39h8cd3c5a_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.44.0=py39h06a4308_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=hc292b87_0
  - pip:
      - altair==5.5.0
      - altair-data-server==0.4.1
      - altair-saver==0.5.0
      - altair-viewer==0.4.0
      - biom-format==2.1.16
      - biopython==1.85
      - certifi==2025.8.3
      - click==8.1.8
      - cvxopt==1.3.1
      - dendropy==5.0.1
      - deprecated==1.2.18
      - ete3==3.1.3
      - future==1.0.0
      - graphtools==1.5.3
      - gseapy==1.1.9
      - ipywidgets==8.1.5
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyterlab-widgets==3.0.13
      - lineageot==0.2.0
      - loess==2.1.2
      - louvain==0.8.2
      - narwhals==2.1.2
      - newick==1.9.0
      - numpy==1.23.5
      - outcome==1.3.0.post0
      - pandas==1.4.2
      - phate==1.0.11
      - plotbin==3.1.7
      - portpicker==1.6.0
      - pot==0.9.5
      - pydot==3.0.4
      - pygsp==0.5.1
      - s-gd2==1.8.1
#      - scib==1.0.0
      - scikit-bio==0.5.6
      - scikit-learn-extra==0.3.0
      - scprep==1.2.3
      - selenium==4.35.0
      - sortedcontainers==2.4.0
      - tasklogger==1.2.0
#      - torch==1.13.1+cu117
      - trio==0.30.0
      - trio-websocket==0.12.2
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - vl-convert-python==1.8.0
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - wsproto==1.2.0
prefix: /data/wenyuhong/anaconda3/envs/DeepTracing
